workflows:
  my-workflow:
    scripts:
      - name: Build Android APK
        working_directory: ./react-native/react-native-demo-project/android
        script: ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/**/*.apk
